apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  POSTGRES_DB: "petclinic"
  POSTGRES_USER: "petclinic"
  POSTGRES_URL: "jdbc:postgresql://postgres:5432/petclinic"