apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: flyvisit/hillel:3.2.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: postgres
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: petclinic-config
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: petclinic-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080