apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: petclinic
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"